apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"hive.openshift.io/managed":"true"},"name":"webhook-validation-cr"},"rules":[{"apiGroups":["admissionregistration.k8s.io"],"resources":["validatingwebhookconfigurations"],"verbs":["list","patch","get","update"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["list","get"]},{"apiGroups":["user.openshift.io"],"resources":["groups"],"verbs":["list","get"]}]}
  creationTimestamp: "2020-12-07T15:13:39Z"
  labels:
    hive.openshift.io/managed: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:hive.openshift.io/managed: {}
      f:rules: {}
    manager: manager
    operation: Update
    time: "2020-12-07T15:13:39Z"
  name: webhook-validation-cr
  resourceVersion: "23789"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/webhook-validation-cr
  uid: 9d3e5d60-e94b-4495-a86a-3722a462010c
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - list
  - patch
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - get
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - list
  - get
